version: "5.0"  

services:
  web:  
    image: hexxa_test_docker:1.0.0
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 256M

    ports:
      - "8080:80"          
    volumes:
      - ./html:/var/www/html:rw
    networks:
      - webserver

networks:
  webserver:  
